version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      check-type-assertions: false
    govet:
      disable:
        - fieldalignment
        - shadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
