name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this feature?
